### ISSUE TITLE
_Originally posted by @MANAALHARBI in https://github.com/pipermerriam/ethereum-function-signature-registry/issues/151_

### ISSUE THREAD

**Issue by MANAALHARBI** [Ellipsis-Labs/solana-verifiable-build#59]
_Originally posted by @MANAALHARBI in https://github.com/pipermerriam/ethereum-function-signature-registry/issues/151_

_Originally posted by @MANAALHARBI in https://github.com/pipermerriam/ethereum-function-signature-registry/issues/152_

**Comment by annajjk88** [comment]
Djdk
